#define ENCODER_A_PINS { GP9 }
#define ENCODER_B_PINS { GP8 }

#define ENCODER_RESOLUTION 1

// RGB_MATRIX conflicts with RGBLIGHT
// #define RGBLIGHT_LAYERS
// #define RGBLIGHT_EFFECT_BREATHING
// #define RGBLIGHT_EFFECT_TWINKLE

#define ENABLE_RGB_MATRIX_SOLID_SPLASH
// #define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_STARLIGHT_SMOOTH
#define ENABLE_RGB_MATRIX_RIVERFLOW
