// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

// Copyright 2025 %YOUR_FULL_NAME% (@%YOUR_GITHUB_USERNAME%)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

enum layer_names {
    // _BASE,
    // _GAMING,
    // _EXTRAS,
    _RJ_BASE,
    _LIGHTS,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // [_BASE] = LAYOUT(
    //     KC_MUTE, KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_VOLD,  KC_VOLU,
    //     LALT(KC_SPC), KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_INS,
    //     KC_HOME, KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_DEL,
    //     KC_END, KC_LCTL, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,  KC_PGUP,
    //     KC_LALT, KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_UP,   KC_PGDN,
    //     MO(_EXTRAS), KC_CAPS, KC_LGUI, TO(_GAMING), KC_SPC,  KC_LALT, TO(_LIGHTS), KC_LCTL, KC_LEFT, KC_DOWN, KC_RGHT
    // ),
    // [_GAMING] = LAYOUT(
    //     KC_F13, KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_F19, KC_LGUI,  TO(_BASE),
    //     KC_F14, KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_INS,
    //     KC_F15, KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_DEL,
    //     KC_F16, KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,  KC_PGUP,
    //     KC_F17, KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_UP,   KC_PGDN,
    //     KC_F18, KC_LCTL, KC_F21, KC_LALT, KC_SPC,  KC_LALT, KC_F20, KC_LCTL, KC_LEFT, KC_DOWN, KC_RGHT
    // ),
    [_RJ_BASE] = LAYOUT(
        UG_TOGG, KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_PSCR, KC_VOLD,  KC_VOLU,
        KC_PGUP, KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC, KC_INS,
        KC_PGDN, KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS, KC_DEL,
        KC_COPY, KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,  KC_HOME,
        KC_PASTE, KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_LSFT, KC_UP,   KC_END,
        KC_MPLY, KC_LCTL, KC_LGUI, KC_LALT, KC_SPC,  KC_RCTL, TO(_LIGHTS), KC_LCTL, KC_LEFT, KC_DOWN, KC_RGHT
    ),
    [_LIGHTS] = LAYOUT(
        QK_BOOT, QK_RBT,  XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX, XXXXXXX,  XXXXXXX,
        XXXXXXX, XXXXXXX,  UG_PREV,    UG_NEXT,    UG_HUED,    UG_HUEU,    UG_SATD,    UG_SATU,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX, XXXXXXX,  XXXXXXX, UG_TOGG,
        XXXXXXX, XXXXXXX,  XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, UG_VALU,   XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, TO(_RJ_BASE), XXXXXXX, UG_SPDD, UG_VALD, UG_SPDU
    ),
    // [_EXTRAS] = LAYOUT(
    //     XXXXXXX, XXXXXXX,  XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,   XXXXXXX,   KC_NUM,   KC_PSLS,   KC_PAST,   KC_PMNS,  XXXXXXX,  XXXXXXX,  XXXXXXX, XXXXXXX,  KC_PWR,
    //     XXXXXXX, XXXXXXX,  XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    KC_P7,    KC_P8,    KC_P9,    KC_PPLS,    XXXXXXX, XXXXXXX,  XXXXXXX, KC_SLEP,
    //     XXXXXXX, XXXXXXX,  MS_BTN1,    MS_UP,    MS_BTN2,    QK_MOUSE_WHEEL_UP,    XXXXXXX,    KC_Y,    KC_P4,    KC_P5,    KC_P6,    KC_PPLS,    XXXXXXX, XXXXXXX, XXXXXXX, KC_WAKE,
    //     XXXXXXX, MS_BTN4, MS_LEFT,    MS_DOWN,    MS_RGHT,    QK_MOUSE_WHEEL_DOWN,    XXXXXXX,    KC_H,    KC_P1,    KC_P2,    KC_P3,    KC_PENT, XXXXXXX, XXXXXXX,  XXXXXXX,
    //     XXXXXXX, MS_BTN5, MS_WHLL,    MS_BTN3,    MS_WHLR,    XXXXXXX,    XXXXXXX,    XXXXXXX,    KC_P0,    KC_P0, KC_PDOT,  KC_PENT, KC_BRID, KC_MSTP,   KC_BRIU,
    //     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, KC_ASST, XXXXXXX, KC_MPRV, KC_MPLY, KC_MNXT
    // ),
};
